version: "3.7"
services:
  app-name:
    build:
      context: .
    image: realtime-plot:0.1.0
    container_name: realtime-plot
    ports:
      - "80:9050"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped